### PR TITLE
Feature: Adding shouldRefresh flag to disable metadata usage

### PR DESCRIPTION
**Pull request by ryaanwells**

### CODE REVIEW

**Comment by suztomo** [comment]
On boolean or enum. If you define enum for that refresh strategy, the library can adopt other strategies you have in mind (https://github.com/mattreid1/firebase_image/issues/4#issuecomment-622558024) in future without breaking its backward compatibility.

**Comment by ryaanwells** [comment]
I'd considered the enum approach to allow multiple refresh strategies, and I agree it's a better long term solution, but decided against it for now as additional refresh strategies may require further refactoring to support. I'd be keen to contribute a strategy approach as a subsequent PR - do you have a use case in mind?

**Comment by suztomo** [comment]
I don’t have specific strategy in my mind.

**Comment by suztomo** [comment]
Thank you for incorporating the suggestion.

**Pull request merged**
